const restaurants = [
	{
		id: "1",
		name: "Shinkanzen Sushi",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/CMYdJBv",
		path: "/restaurant/1",
		foodOrigin: "Japan",
		priceRange: "$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "2",
		name: "KFC",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/56Y6mmt",
		path: "/restaurant/2",
		foodOrigin: "America",
		priceRange: "$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "3",
		name: "Taco Bell",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/QjYFnsU",
		path: "/restaurant/3",
		foodOrigin: "Mexico",
		priceRange: "$$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "4",
		name: "Pepper Lunch",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/toXNTKo",
		path: "/restaurant/4",
		foodOrigin: "America",
		priceRange: "$$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "5",
		name: "The Spicy House",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/v3Dq4Xj",
		path: "/restaurant/5",
		foodOrigin: "China",
		priceRange: "$$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "6",
		name: "ตํ่ามั่ว",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/FGQHi9H",
		path: "/restaurant/6",
		foodOrigin: "Thai",
		priceRange: "$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "7",
		name: "SSamthing Together",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/Zm9ZyEc",
		path: "/restaurant/7",
		foodOrigin: "Japan",
		priceRange: "$$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "8",
		name: "GuGu Chicken",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/s914scY",
		path: "/restaurant/8",
		foodOrigin: "Korea",
		priceRange: "$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "9",
		name: "K-StrEAT",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/hLzikKh",
		path: "/restaurant/9",
		foodOrigin: "Korea",
		priceRange: "$$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "10",
		name: "CoCo ICHIBANYA",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/VxnW5W4",
		path: "/restaurant/10",
		foodOrigin: "Japan",
		priceRange: "$$",
		tags: [],
		location: "Samyan Mitrtown",
	},
	{
		id: "11",
		name: "เฮงยอดผัก",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.wongnai.com/r/224224Lz",
		path: "/restaurant/11",
		foodOriigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "สวนหลวงสแควร์",
	},
	{
		id: "12",
		name: "ร้านเจ๊โอว",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/FX9fQx6",
		path: "/restaurant/12",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Charat Mueang Road",
	},
	{
		id: "13",
		name: "Dazhong Hotpot & BBQ",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.facebook.com/p/%E0%B8%95%E0%B9%89%E0%B8%B2%E0%B8%88%E0%B9%89%E0%B8%87-Dazhong-Hotpot-BBQ-61558058133819/?locale=th_TH",
		path: "/restaurant/13",
		foodOrigin: "China",
		priceRange: "$$",
		tags: [],
		location: "Chula 5",
	},
	{
		id: "14",
		name: "Shall we Meet&Eat",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.facebook.com/ShallweMeetandEat/?locale=th_TH",
		path: "/restaurant/14",
		foodOrigin: "Japan",
		priceRange: "$$",
		tags: [],
		location: "Chula 14",
	},
	{
		id: "15",
		name: "โจ๊กสามย่าน",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/zhqhfYF",
		path: "/restaurant/15",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Banthat Thong Road",
	},
	{
		id: "16",
		name: "ส้มตำเจ๊อ้อย",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/Xq5FRHv",
		path: "/restaurant/16",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 20",
	},
	{
		id: "17",
		name: "Chula 50 Kitchen",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/CCbXj1n",
		path: "/restaurant/17",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 50",
	},
	{
		id: "18",
		name: "T.Spoon",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.wongnai.com/r/74577Ye",
		path: "/restaurant/18",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 50",
	},
	{
		id: "19",
		name: "Guo Tzi",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.facebook.com/p/Guo-Tzi-Restaurant-%E6%9E%9C%E5%AD%90%E9%A4%90%E5%BB%B3-100063767747151/",
		path: "/restaurant/19",
		foodOrigin: "Taiwan",
		priceRange: "$$",
		tags: [],
		location: "Chula 48",
	},
	{
		id: "20",
		name: "ครัวจุฬา 48 เชฟเม้ง",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/6YkUbkd",
		path: "/restaurant/20",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 48",
	},
	{
		id: "21",
		name: "อิมจัง",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/hLhYRyb",
		path: "/restaurant/21",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 50",
	},
	{
		id: "22",
		name: "เจ๊แอน คอหมูย่าง",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/LQYsRpp",
		path: "/restaurant/22",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 50",
	},
	{
		id: "23",
		name: "เกาเหลาสามหมู ข้าวขาหมูร้อยอาจารย์",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.wongnai.com/r/64734lY",
		path: "/restaurant/23",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 18",
	},
	{
		id: "24",
		name: "Pasta & Hamburg",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/dhbF6wo",
		path: "/restaurant/24",
		foodOrigin: "Italy",
		priceRange: "$",
		tags: [],
		location: "Chula 3",
	},
	{
		id: "25",
		name: "Pasta(จุฬา) By...CAT",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://www.wongnai.com/r/2486794Kn",
		path: "/restaurant/25",
		foodOrigin: "Italy",
		priceRange: "$$",
		tags: [],
		location: "Chula 14",
	},
	{
		id: "26",
		name: "นายยิ๊งเจ้าเก่า เกาเหลาเลือดหมู",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/seGZZzk",
		path: "/restaurant/26",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 9",
	},
	{
		id: "27",
		name: "ลือชาข้าวหมูแดงนครปฐมสามย่าน",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/LLZgB3H",
		path: "/restaurant/27",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 48",
	},
	{
		id: "28",
		name: "Soi 6 Pochana",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/adnF5Xk",
		path: "/restaurant/28",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Chula 11",
	},
	{
		id: "29",
		name: "Curry boy",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/GKgizbX",
		path: "/restaurant/29",
		foodOrigin: "Japan",
		priceRange: "$$",
		tags: [],
		location: "Chula 42",
	},
	{
		id: "30",
		name: "Hokki Phochana",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/LhDbGmr",
		path: "/restaurant/30",
		foodOrigin: "Chinese",
		priceRange: "$$$",
		tags: [],
		location: "Chula 34",
	},
	{
		id: "31",
		name: "Rod Dee Ded Ban Khun Nop",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/K9m6D2Z",
		path: "/restaurant/31",
		foodOrigin: "Thai",
		priceRange: "$$$",
		tags: [],
		location: "Charoen Mueang Road",
	},
	{
		id: "32",
		name: "ร้านเจ๊แหม่มตามสั่ง",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/uWKMtYp",
		path: "/restaurant/32",
		foodOrigin: "Thhai",
		priceRange: "$",
		tags: [],
		location: "Chula 34",
	},
	{
		id: "33",
		name: "Longleng Noodle",
		imageUrl: "/shared/restaurant_pictures/0_restaurant.png",
		link: "https://g.co/kgs/Sq5YECR",
		path: "/restaurant/33",
		foodOrigin: "Thai",
		priceRange: "$",
		tags: [],
		location: "Banthat Thong Road",
	},
];

export default restaurants;
